// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dizisffgmpsrymozrvtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpemlzZmZnbXBzcnltb3pydnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTkzMDksImV4cCI6MjA1OTU3NTMwOX0.540202EfngEy-wmDhQVAxsVbrVrPXUUh7YhN-yS1hUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);